support for docker compose v2 and backwards compatibility for v1

diff --git a/identity b/identity
--- a/identity
+++ b/identity
@@ -7,8 +7,6 @@ Yellow='\033[0;33m'
 BYellow='\033[1;33m'
 NC='\033[0m'
 
-docker_compose="docker-compose -p identity -f docker-compose.identity.yml --log-level ERROR"
-
 function outputLogo {
 echo "
 
@@ -92,10 +90,17 @@ then
     exit 1
 fi
 
-if ! docker-compose -v &> /dev/null
-then
-    echo -e "${Red}Error: docker-compose is required: https://docs.docker.com/compose/install/"
-    exit 2
+if command -v docker compose &> /dev/null 
+then 
+  docker_compose="docker compose -p identity -f docker-compose.identity.yml"
+else
+  if command -v docker-compose&> /dev/null
+  then
+    docker_compose="docker-compose -p identity -f docker-compose.identity.yml --log-level ERROR"
+  else
+    echo -e "${Red}Error: docker compose is required: https://docs.docker.com/compose/install/"
+    exit 2 
+  fi
 fi
 
 STRATOGS_REQUIRED_VERSION=$(grep strato-getting-started-min-version docker-compose.identity.yml | awk -F":" '{print $NF}')
