Fix the compose version detection

diff --git a/payment-server b/payment-server
--- a/payment-server
+++ b/payment-server
@@ -91,16 +91,16 @@ then
     exit 1
 fi
 
-if ! docker-compose -v &> /dev/null
+if ! docker compose version  &> /dev/null && ! docker-compose -v  &> /dev/null
 then
-    echo -e "${Red}Error: docker-compose is required: https://docs.docker.com/compose/install/"
+    echo -e "${Red}Error: Docker Compose is required: https://docs.docker.com/compose/install/"
     exit 2
 else
   if ! docker compose version &> /dev/null
   then
     docker_compose="docker-compose -p payment-server -f docker-compose.payment.yml --log-level ERROR"
   else
-    docker_compose="docker compose -p payment-server -f docker-compose.payment.yml"
+    docker_compose="docker -l error compose -p payment-server -f docker-compose.payment.yml"
   fi
 fi
 
diff --git a/vault b/vault
--- a/vault
+++ b/vault
@@ -123,9 +123,9 @@ then
     exit 1
 fi
 
-if ! docker-compose -v &> /dev/null
+if ! docker compose version  &> /dev/null && ! docker-compose -v  &> /dev/null
 then
-    echo -e "${Red}Error: docker-compose is required: https://docs.docker.com/compose/install/"
+    echo -e "${Red}Error: Docker Compose is required: https://docs.docker.com/compose/install/"
     exit 2
 else
   if ! docker compose version &> /dev/null
@@ -133,7 +133,7 @@ else
     docker_compose="docker-compose -p vault -f docker-compose.vault.yml --log-level ERROR"
     CNAME_SEP="_"
   else
-    docker_compose="docker compose -p vault -f docker-compose.vault.yml"
+    docker_compose="docker -l error compose -p vault -f docker-compose.vault.yml"
     CNAME_SEP="-"
   fi
 fi
